In [1]:
import numpy as np

In [2]:
list1=[1,3,5,6,7]

In [3]:
type(list1)

list

In [4]:
np.array(list1)

array([1, 3, 5, 6, 7])

In [5]:
list2=[[1,2,3,4,],[6,5,4,3,],[8,7,4,3,],[5,7,9,4]]

In [6]:
list2

[[1, 2, 3, 4], [6, 5, 4, 3], [8, 7, 4, 3], [5, 7, 9, 4]]

In [7]:
np.array(list2)

array([[1, 2, 3, 4],
       [6, 5, 4, 3],
       [8, 7, 4, 3],
       [5, 7, 9, 4]])

In [8]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [9]:
np.arange(1,21,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros((4,4,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((4,4,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [14]:
np.linspace(10,100,5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(2)

array([0.7527295 , 0.99093519])

In [17]:
np.random.rand(5,5)

array([[0.23904823, 0.73978155, 0.07715992, 0.38971859, 0.33057785],
       [0.97166715, 0.95105034, 0.63828146, 0.0264434 , 0.69488739],
       [0.88112414, 0.33546763, 0.83149064, 0.71653365, 0.42391798],
       [0.36516015, 0.7159877 , 0.57113242, 0.02026666, 0.49033962],
       [0.09251673, 0.31772184, 0.49302154, 0.12255008, 0.66567015]])

In [18]:
np.random.randint(10,100)

39

In [19]:
np.random.randint(10,100,10)

array([49, 34, 48, 45, 93, 23, 43, 18, 96, 14])

In [22]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
np.random.randint(1,100)

55

In [25]:
arr=np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
np.arange(25)

In [30]:
narr=np.random. randint(5,100,10)

In [31]:
narr

array([61, 70, 90, 27, 44, 91, 59, 26, 82, 63])

In [33]:
narr.max()

91

In [34]:
narr.argmax()

5

In [35]:
narr.min()

26

In [36]:
narr.argmin()

7

In [38]:
narr.reshape(10,1).shape

(10, 1)

In [39]:
narr.dtype

dtype('int32')