In [6]:
import numpy as np

In [2]:
list1=np.arange(1,15)

In [3]:
list1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
list1>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [5]:
list2=list1>4

In [6]:
list2

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [7]:
list1[list2]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
z=5

In [9]:
list1[list1>z]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
arr=np.arange(0,10)

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
arr**arr

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [16]:
arr/arr

C:\Users\HP\AppData\Local\Temp\ipykernel_14216\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [17]:
1/arr

C:\Users\HP\AppData\Local\Temp\ipykernel_14216\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [36]:
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [38]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [40]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [42]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [44]:
np.log(arr)

C:\Users\HP\AppData\Local\Temp\ipykernel_14216\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [46]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [48]:
np.sin(90)

0.8939966636005579

In [50]:
np.log(100)

4.605170185988092

In [66]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [68]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [70]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [152]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [112]:
np.random.rand(1)

array([0.12360137])

In [114]:
np.random .rand(25)

array([0.20149574, 0.99784684, 0.61396513, 0.57623573, 0.11726221,
       0.30635527, 0.46001915, 0.67462438, 0.97215257, 0.27333494,
       0.03570107, 0.65697007, 0.69694469, 0.43934421, 0.32744745,
       0.63811777, 0.78107105, 0.55256023, 0.29584466, 0.45063412,
       0.28501049, 0.74841837, 0.41672829, 0.10769604, 0.35381998])

In [128]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [154]:
list1=np.arange(1,10)

In [156]:
list1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
np.sum(list1)

45

In [160]:
list2=np.arange(1,26).reshape(5,5)

In [162]:
list2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [172]:
sum_column=np.sum(list2,axis=0   )

In [168]:
sum_column

array([55, 60, 65, 70, 75])

In [7]:
matrix=np.arange(0,1,.01)

In [8]:
matrix

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [11]:
matrix.reshape(10,10)

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [12]:
matrix2=np.arange(0,1,.01).reshape(10,10)

In [13]:
matrix2

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])