In [8]:
import numpy as np

In [9]:
list1=np.random.randint(100,1000,100)

In [10]:
list1

array([129, 665, 819, 736, 225, 189, 888, 881, 844, 540, 332, 277, 390,
       692, 791, 486, 953, 275, 817, 725, 721, 349, 670, 757, 579, 181,
       701, 888, 572, 831, 968, 985, 510, 554, 990, 508, 789, 745, 340,
       349, 475, 546, 162, 226, 965, 383, 221, 286, 125, 733, 718, 645,
       303, 685, 249, 105, 630, 200, 657, 332, 239, 766, 154, 868, 299,
       332, 238, 183, 547, 775, 880, 673, 411, 161, 467, 494, 673, 508,
       493, 789, 814, 676, 205, 776, 347, 724, 806, 483, 982, 168, 629,
       562, 306, 896, 337, 861, 330, 728, 818, 399])

In [30]:
matrix=list1.reshape(5,5,4)

In [29]:
matrix.shape

(5, 5, 4)

In [31]:
matrix

array([[[129, 665, 819, 736],
        [225, 189, 888, 881],
        [844, 540, 332, 277],
        [390, 692, 791, 486],
        [953, 275, 817, 725]],

       [[721, 349, 670, 757],
        [579, 181, 701, 888],
        [572, 831, 968, 985],
        [510, 554, 990, 508],
        [789, 745, 340, 349]],

       [[475, 546, 162, 226],
        [965, 383, 221, 286],
        [125, 733, 718, 645],
        [303, 685, 249, 105],
        [630, 200, 657, 332]],

       [[239, 766, 154, 868],
        [299, 332, 238, 183],
        [547, 775, 880, 673],
        [411, 161, 467, 494],
        [673, 508, 493, 789]],

       [[814, 676, 205, 776],
        [347, 724, 806, 483],
        [982, 168, 629, 562],
        [306, 896, 337, 861],
        [330, 728, 818, 399]]])

In [32]:
matrix.shape

(5, 5, 4)

In [39]:
matrix[1,3:,:]

array([[510, 554, 990, 508],
       [789, 745, 340, 349]])

In [43]:
matrix[0,0,2::]

array([819, 736])

In [49]:
matrix[1,3:,:2]

array([[510, 554],
       [789, 745]])

In [50]:
matrix[4,1,1]

724

In [53]:
matrix[3,1:3,2:]

array([[238, 183],
       [880, 673]])

In [54]:
list2=np.arange(1,11)

In [55]:
list2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
list3=list2.copy()

In [59]:
list3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
list7=np.zeros((10,10))

In [10]:
list7

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
list7.shape[1]

10

In [29]:
for i in range(1,10):
     list7[i]=i
list7

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])